tipo = input("digite um numero inteiro: ")
print(type(tipo))
print ("So tem espaços? :", tipo.isspace())
print("e alfanumerico? :", tipo.isalnum())
print("e alfabetico? :", tipo.isalpha())
print("e numerico? :", tipo.isnumeric())
print(" e maiusculas? :", tipo.upper())
print(" e minusculas? :", tipo.lower())
print('esta capitalizada? :', tipo.title())