#Faça um programa que leia um número inteiro qualquer e mostre na tela sua tabuada
num = int(input("Digite um numero para ver a tabuada: "))
um = num * 1
dois =  num * 2
treis = num * 3
quatro = num * 4
cinco = num * 5
seis = num * 6
sete = num * 7
oito = num * 8
nove = num * 9
dez = num * 10
print("{} x {} = {}".format(num,1,um))
print("{} x {} = {}".format(num,2,dois))
print("{} x {} = {}".format(num,3,treis))
print("{} x {} = {}".format(num,4,quatro))
print("{} x {} = {}".format(num,5,cinco))
print("{} x {} = {}".format(num,6,seis))
print("{} x {} = {}".format(num,7,sete))
print("{} x {} = {}".format(num,8,oito))
print("{} x {} = {}".format(num,9,nove))
print("{} x {} = {}".format(num,10,dez))